apiVersion: v1
kind: Service
metadata:
  name: {{ include "release-finder.fullname" . }}
  labels:
    {{- include "release-finder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{ end }}
  selector:
    {{- include "release-finder.selectorLabels" . | nindent 4 }}
